//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Car
    {
        public int CarID { get; set; }

        [Display(Name = "Model")]
        [Required(ErrorMessage ="Please enter a model:")]
        public int C_fk_CarModel { get; set; }

        [Display(Name = "Make")]
        [Required(ErrorMessage = "Please enter a make:")]
        public int C_fk_CarMake { get; set; }

        [Display(Name = "Colour")]
        [Required(ErrorMessage = "Please enter a colour:")]
        public int C_fk_CarColour { get; set; }

        [Display(Name ="Engine Size")]
        [Required(ErrorMessage = "Please enter an engine size:")]
        public double CarEngine { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual CarMake CarMake { get; set; }
        public virtual Colour Colour { get; set; }
    }
}
